
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
      # - image: circleci/python:3.10
      # - image: circleci/postgres:13
      #   environment:
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres
      #     POSTGRES_DB: test_db
    steps:
      - checkout

      - run:
          name: Set up dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run Migrations
          command: |
            python manage.py migrate

      - run:
          name: Code Formatter
          command: |
            python manage.py codeFormatting django_project/settings.py

      - run:
          name: Run Linter
          command: |
            pip install flake8
            flake8 .

      - run:
          name: Run Code Analysis
          command: |
            git ls-files | grep -v 'migrations' | grep -v 'settings.py' | grep -v 'manage.py' | grep -E '.py$' | xargs pylint -E --load-plugins=pylint_django

      - run:
          name: Run Tests
          command: |
            python manage.py test --verbosity 2 --failfast

      - run:
          name: Run Security Checks
          command: |
            python manage.py check --deploy --fail-level ERROR

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: django-application
